// WordPress webpack config.
const defaultConfig = require( '@wordpress/scripts/config/webpack.config' );

// Plugins.
const RemoveEmptyScriptsPlugin = require( 'webpack-remove-empty-scripts' );
const CopyWebpackPlugin = require('copy-webpack-plugin');

// Utilities.
const path = require( 'path' );

// Add any new entry points by extending the webpack config.
module.exports = {
    ...defaultConfig,
    ...{
        entry: {
            'js/main':  path.resolve( process.cwd(), 'resources/js',   'main.js'   ),
            'css/styles': path.resolve( process.cwd(), 'resources/scss', 'styles.scss' ),
        },
        plugins: [
            // Include WP's plugin config.
            ...defaultConfig.plugins,

            // Removes the empty `.js` files generated by webpack but
            // sets it after WP has generated its `*.asset.php` file.
            new RemoveEmptyScriptsPlugin( {
                stage: RemoveEmptyScriptsPlugin.STAGE_AFTER_PROCESS_PLUGINS
            } ),
            //Copy images to a public folder
            new CopyWebpackPlugin({
                patterns: [
                    {
                        from: path.resolve(process.cwd(), 'resources/images'),
                        to: path.resolve(process.cwd(), 'public/images'),
                    },
                ],
            }),
        ]
    }
};
